### ============================================
### CONFIGURAÇÃO
### ============================================
@baseUrl = http://localhost:3000
@contentType = application/json
# @userId = Bnr6l93HzkTpwXlb2xAhAe2N1h29jWgD esse é o ID do Rogério
# @userId = IFvTaXaQxlc54KfyA97dlbUj7CvPtjfR esse é o ID do Rafael
@userId = Bnr6l93HzkTpwXlb2xAhAe2N1h29jWgD
@sessionToken = 3YNW2ZwQ0i7knsv1kZlyoVvHipiXqkNK.URvpthv7DAQMjmx%2F%2F40vjuzQBNkQRlqK4NcvPcjXzyg%3D

### ============================================
### TESTE DE AUTENTICAÇÃO
### ============================================

### GET - Verificar usuário logado e role - OK
GET {{baseUrl}}/api/auth/me
Content-Type: {{contentType}}
Cookie: better-auth.session_token={{sessionToken}}
### ========================================================================================

### ============================================
### USUÁRIOS
### ============================================

### GET - BUSCAR TODOS OS USUÁRIO
GET {{baseUrl}}/api/users
Content-Type: {{contentType}}
Cookie: better-auth.session_token={{sessionToken}}
### ===

### GET - BUSCAR USUÁRIO ESPECÍFICO
GET {{baseUrl}}/api/users/{{userId}}
Content-Type: {{contentType}}
Cookie: better-auth.session_token={{sessionToken}}
### ========================================================================================





### ============================================
### PASSO 1: CRIAR PATROCINADOR
### ============================================

### POST - Criar patrocinador
POST {{baseUrl}}/api/sponsors
Content-Type: {{contentType}}
Cookie: better-auth.session_token={{sessionToken}}

{
  "name": "Nesha Store",
  "slug": "nesha-store",
  "couponCode": "TARUHNESHASTORE10",
  "logoUrl": "/logotipo-nesha-store-1.jpg",
  "isActive": true
}
### =====

# Após executar o POST, copie o "id" da resposta e cole abaixo:
@sponsorId = cmi0h91gk0000759gfm2jfxt4
@sponsorSlug = csgo-net
# @sponsorId = cmi0h91gk0000759gfm2jfxt4 - esse ID é da CSGO.Net
# @sponsorId = cmiuw1n42000075zoz9gvgxh2 - esse ID é da Nesha Store
# @sponsorId = cmixhrb0500007538ifviwrq5 - esse ID é da Skins monkey

### GET - Listar todos os patrocinadores
GET {{baseUrl}}/api/sponsors
Content-Type: {{contentType}}
Cookie: better-auth.session_token={{sessionToken}}
###

### GET - Buscar patrocinador específico pelo slug
GET {{baseUrl}}/api/sponsors/by-slug/{{sponsorSlug}}
Content-Type: {{contentType}}
###
### ========================================================================================





### ============================================
### PASSO 2: CRIAR SORTEIO
### ============================================

### POST - Criar sorteio
POST {{baseUrl}}/api/raffles
Content-Type: {{contentType}}
Cookie: better-auth.session_token={{sessionToken}}

{
  "sponsorId": "{{sponsorId}}",
  "title": "Sorteio AK-47 Redline",
  "description": "Concorra a uma AK-47 Redline Field-Tested",
  "skinName": "AK-47 Redline Field-Tested",
  "skinImage": "https://via.placeholder.com/300",
  "skinValue": 150.00,
  "startDate": "2026-01-15T00:00:00.000Z",
  "endDate": "2026-02-15T23:59:59.000Z"
}
###

# Após executar o POST, copie o "id" da resposta e cole abaixo:
@raffleId = cmkifs8q5000275k4eiux4ayg

### GET - Listar todos os sorteios ativos
GET {{baseUrl}}/api/raffles
Content-Type: {{contentType}}
Cookie: better-auth.session_token={{sessionToken}}
###

### GET - Buscar sorteio específico - OK
GET {{baseUrl}}/api/raffles/{{raffleId}}
Content-Type: {{contentType}}
Cookie: better-auth.session_token={{sessionToken}}
###
### ========================================================================================





### ============================================
### PASSO 3: CRIAR DEPÓSITO
### ============================================

### POST - Criar depósito
POST {{baseUrl}}/api/deposits
Content-Type: {{contentType}}
Cookie: better-auth.session_token={{sessionToken}}

{
  "userId": "{{userId}}",
  "sponsorId": "{{sponsorId}}",
  "raffleId": "{{raffleId}}",
  "amount": 150.00,
  "proofImage": "https://via.placeholder.com/600/0000FF/FFFFFF?text=Comprovante+PIX"
}
###

# Após executar o POST, copie o "id" da resposta e cole abaixo:
@depositId = cmixm1bjk00017534b7t8sq1c

### GET - Listar os depósitos do usuário - OK
GET {{baseUrl}}/api/deposits?userId={{userId}}
Content-Type: {{contentType}}
Cookie: better-auth.session_token={{sessionToken}}
###

### GET - Buscar depósito específico - OK
GET {{baseUrl}}/api/deposits/{{depositId}}
Content-Type: {{contentType}}
Cookie: better-auth.session_token={{sessionToken}}
###
### ========================================================================================

### ============================================
### PASSO 4: TESTAR APROVAÇÃO
### ============================================

### PATCH - Aprovar depósito (ADMIN) - OK
PATCH {{baseUrl}}/api/deposits/{{depositId}}/approve
Content-Type: {{contentType}}
Cookie: better-auth.session_token={{sessionToken}}
###

### PATCH - Rejeitar depósito (ADMIN) - OK
PATCH {{baseUrl}}/api/deposits/{{depositId}}/reject
Content-Type: {{contentType}}
Cookie: better-auth.session_token={{sessionToken}}
###
### ========================================================================================

### ============================================
### PASSO 5: TESTAR SORTEIO
### ============================================

### POST - Realizar sorteio (draw) - OK
POST {{baseUrl}}/api/raffles/{{raffleId}}/draw
Content-Type: {{contentType}}
Cookie: better-auth.session_token={{sessionToken}}
### ==========
### ========================================================================================

### ============================================
### CONSULTAS (GET)
### ============================================

### GET - Buscar entradas do usuário em um sorteio
GET {{baseUrl}}/api/raffles/{{raffleId}}/entries?userId={{userId}}
Content-Type: {{contentType}}
Cookie: better-auth.session_token={{sessionToken}}

